CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
  user_id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), 
  email VARCHAR(100) UNIQUE NOT NULL, 
  hash VARCHAR(60) NOT NULL
);